---
kind: pipeline
name: push

steps:
- name: test
  image: alpine
  commands:
  - echo "It works!"
  

trigger:
  event:
  - push
  
---
  
kind: pipeline
name: crawler.tosdr.org

steps:
- name: amd64
  image: plugins/docker
  settings:
    auto_tag: true
    username: 
        from_secret: jbackpcat_username
    password: 
        from_secret: jbackpcat_password
    repo: jbackpcat/crawler.tosdr.org
    dockerfile: crawler.tosdr.org/Dockerfile
