---
kind: pipeline
name: push

steps:
- name: test
  image: alpine
  commands:
  - echo "It works!"
  

trigger:
  event:
  - push
  
---
  
kind: pipeline
name: crawler.tosdr.org

steps:

- name: tags
  image: alpine
  commands:
  - if [[ -v tags ]]; then echo -n $tags > .tags; else echo latest > .tags; fi

- name: amd64
  image: plugins/docker
  settings:
    username: 
        from_secret: jbackpcat_username
    password: 
        from_secret: jbackpcat_password
    repo: jbackpcat/crawler.tosdr.org
    dockerfile: crawler.tosdr.org/Dockerfile


trigger:
  target:
  - crawler.tosdr.org